from . import delivery_instruction_line
from . import inherit_inventory_stock
from . import inherited_purchase_order
from . import material_request
from . import product_siv
from . import purchase_quotation
from . import purchase_request
from . import supplier_analysis
from . import quality_inspection
from . import res_users_settings
from . import res_config_settings
from . import supplier_analysis_threshold