from odoo import _, api, fields, models
from collections import defaultdict
from odoo.exceptions import ValidationError, UserError
from odoo.osv.expression import AND

from datetime import datetime, timedelta
import pdb



class QualityInspection(models.Model):
    _name = "quality.inspection"
    _description = "Quality Inspection"
    _inherit = ["mail.thread", "mail.activity.mixin", "analytic.mixin"]

    name = fields.Char("Reference", required=True, readonly=True, default=lambda self: _('New'))
    state = fields.Selection([
        ('draft', 'Generated'),
        ('requested_docs', 'Submitted'),
        ('approved', 'Approved'),
        ('failed', 'Failed')
    ], string="Status", default='draft', required=True)
    requested_date = fields.Date("Requested Date", readonly=True)
    inspected_date = fields.Date("Approved Date", readonly=True)
    inspected_by = fields.Many2one("res.users", string="Generated By", readonly=True, default=lambda self: self.env.user)
    partner_id = fields.Many2one("res.partner", string="Vendor", required=True)
    supplier_analysis_id = fields.Many2one("supplier.analysis", string="Supplier Analysis", required=True)
    quality_inspections_line_ids = fields.One2many("quality.inspection.line", "quality_inspection_id", string="Inspection Lines")

    @api.model
    def create(self, vals):
        """Generate a unique name for each quality inspection."""
        if vals.get('name', _('New')) == _('New'):
            vals['name'] = self.env['ir.sequence'].next_by_code('quality.inspection') or _('New')
        return super(QualityInspection, self).create(vals)
    
   
    def action_request_documents(self):
        """Transition the record to the 'Requested' state."""
        if self.state != 'draft':
            raise UserError(_("Only records in the 'Draft' state can request documents."))
        self.write({
            'state': 'requested_docs',
            'requested_date': fields.Date.today(),
        })



    def action_approve(self):
        """Transition the record to the 'Approved' state with enhanced notifications."""
        if self.state != 'requested_docs':
            raise UserError(_("You can only approve records that have been submitted."))
        if not self.quality_inspections_line_ids:
            raise UserError(_("No lines to approve."))
        
        passed_count = 0
        failed_count = 0
        
        for line in self.quality_inspections_line_ids:
            if not line.passed_inspection and not line.failed_inspection:
                raise UserError(_("All lines must be passed or failed."))

            if line.passed_inspection:
                line.supplier_analysis_line_id.passed_inspection = True
                passed_count += 1
            else:
                line.supplier_analysis_line_id.passed_inspection = False
                failed_count += 1
                
        self.write({
            'state': 'approved',
            'inspected_date': fields.Date.today(),
            'inspected_by': self.env.user.id,
        })

    def action_reset_to_draft(self):
        """Reset the record back to the 'Draft' state."""
        if self.state == 'draft':
            raise UserError(_("The record is already in the 'Draft' state."))
        self.write({'state': 'draft'})

    def has_failed_items(self):
        """Check if this quality inspection has any failed items"""
        self.ensure_one()
        return bool(self.quality_inspections_line_ids.filtered(lambda l: l.failed_inspection))

    def has_passed_items(self):
        """Check if this quality inspection has any passed items (and no failed items)"""
        self.ensure_one()
        has_passed = bool(self.quality_inspections_line_ids.filtered(lambda l: l.passed_inspection))
        has_failed = bool(self.quality_inspections_line_ids.filtered(lambda l: l.failed_inspection))
        return has_passed and not has_failed


class QualityInspectionLine(models.Model):
    _name = "quality.inspection.line"
    _description = "Quality Inspection Line"

    quality_inspection_id = fields.Many2one("quality.inspection", string="Quality Inspection")
    supplier_analysis_line_id = fields.Many2one("supplier.analysis.line", string="Supplier Analysis Line")
    partner_id = fields.Many2one("res.partner", string="Vendor", compute="_compute_partner_id", store=True, readonly=True)
    product_id = fields.Many2one('product.product', string="Product", required=True)
    name = fields.Char("Description")
    
    inspection_status = fields.Selection([
        ('passed', 'Passed'),
        ('failed', 'Failed'),
        ('pending', 'Pending')
    ], string="Inspection Status", default='pending')

    passed_inspection = fields.Boolean("Passed Inspection", compute='_compute_inspection_flags', inverse='_inverse_inspection_flags', store=True)
    failed_inspection = fields.Boolean("Failed Inspection", compute='_compute_inspection_flags', inverse='_inverse_inspection_flags', store=True)

    inspection_remark = fields.Char("Inspection Remark")

    @api.depends('supplier_analysis_line_id.partner_id')
    def _compute_partner_id(self):
        """Get vendor from the related supplier analysis line"""
        for record in self:
            record.partner_id = record.supplier_analysis_line_id.partner_id if record.supplier_analysis_line_id else False

    @api.depends('inspection_status')
    def _compute_inspection_flags(self):
        for record in self:
            record.passed_inspection = (record.inspection_status == 'passed')
            record.failed_inspection = (record.inspection_status == 'failed')

    def _inverse_inspection_flags(self):
        """Update inspection_status based on passed_inspection or failed_inspection changes"""
        # Skip if we're updating from inspection_status to prevent recursion
        if self.env.context.get('from_inspection_status_update'):
            return
        
        for record in self:
            # If passed is True, set status to passed and clear failed
            if record.passed_inspection:
                record.with_context(from_inspection_status_update=True).inspection_status = 'passed'
                if record.failed_inspection:
                    record.with_context(from_inspection_status_update=True).failed_inspection = False
            # If failed is True, set status to failed and clear passed
            elif record.failed_inspection:
                record.with_context(from_inspection_status_update=True).inspection_status = 'failed'
                if record.passed_inspection:
                    record.with_context(from_inspection_status_update=True).passed_inspection = False
            # If both are False and status was passed/failed, set to pending
            elif not record.passed_inspection and not record.failed_inspection:
                if record.inspection_status in ['passed', 'failed']:
                    record.with_context(from_inspection_status_update=True).inspection_status = 'pending'

    @api.constrains('passed_inspection', 'failed_inspection')
    def _check_mutually_exclusive(self):
        """Ensure only one of passed or failed can be selected at a time"""
        for record in self:
            if record.passed_inspection and record.failed_inspection:
                raise ValidationError(_("You can only select either 'Passed' or 'Failed', not both."))



class SupplierAnalysis(models.Model):
    
    _inherit = "supplier.analysis"


    quality_inspection_ids = fields.One2many("quality.inspection", "supplier_analysis_id", string="Quality Inspections")


    def action_view_quality_inspection(self):
        return {
            'type': 'ir.actions.act_window',
            'name': 'Quality Inspection',
            'res_model': 'quality.inspection',
            'view_mode': 'list,form',
            'domain': [('supplier_analysis_id', '=', self.id)],
        }

    quality_inspection_count = fields.Integer("Quality Inspection Count", compute='_compute_quality_inspection_count')
    @api.depends('quality_inspection_ids')
    def _compute_quality_inspection_count(self):
        for record in self:
            record.quality_inspection_count = len(record.quality_inspection_ids)
    
